version: '3'

networks:
  laravel:

services:

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - php
      - mysql
    ports:
      - "180:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  #MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel


  #PHP Service
  php:
    # build instead of using an existing image on the hub
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: jguyomard/laravel-php:7.3
#registry.gitlab.com/biscofil/docker_laravel_test
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "19000:9000"
    networks:
      - laravel
