version: '3.8'

services:
  trigger_warning_app:
    image: biscofil/trigger_warning:latest
    container_name: trigger_warning_app
    ports:
      - "8000:80"
    environment:
      - DEBUG=True
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/db.sqlite
    volumes:
      - ./storage-volume:/var/www/html/storage
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data: