apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/laravel: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: homestead
            - name: MYSQL_PASSWORD
              value: secret
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: homestead
            - name: SERVICE_NAME
              value: mysql
            - name: SERVICE_TAGS
              value: dev
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/mysql/
              name: mysql-claim
      restartPolicy: Always
      volumes:
        - name: mysql-claim
          persistentVolumeClaim:
            claimName: mysql-claim
status: {}
