apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql
  name: {{ .Values.database.service.name }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
